[package]
name = "chess"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.12.1"
minifb = "0.25.0"
strum = "0.26.2"
strum_macros = "0.26.2"
